### ISSUE TITLE
[Feature] : Cursor를 이용한 주문 내역 및 상태 조회 API - v3

### ISSUE THREAD

**Issue by jinoo7099** [boostcampwm-2022/web29-Buddha#162]
## 💁 설명
Cursor를 이용한 주문 내역 및 상태 조회 API. 주문 내역 및 상태 조회 api를 리팩토링한다.

### redis 자료 구조
- 고객이 상태를 확인하기 위한 데이터와, 점주가 업데이트하는 데이터를 분리한다.
- 점주측은 cafe1Manager, 고객은 cafe1Client라는 key로 필드에 접근한다.
- 점주측 필드는 sortedset을 활용한다. sortedSet 내의 value 구조는 미정
- 고객은 set을 활용한다.
### 점주측 새 주문 확인 api
- cursor 기반으로 동작한다.
- 새로고침, 로그인, 혹은 현재 아무 주문이 없다면 ''을, 그게 아니라면 현재 가지고 있는 주문 중 가장 높은 pk를 보낸다.
- 서버는 이를 확인하고, 해당 pk 이후의 주문 데이터를 '모두' 내려준다. (pagination x)
- 점주는 새로 내려진 데이터를 requested 목록에서 추가로 확인할 수 있다.
### 고객측 주문 상태 api
- 고객은 상태를 조회하고자 하는 주문의 id와 카페 id를 함께 보낸다.
- redis에서 이를 조회한다. 없다면 캐싱

## 📑 체크리스트
> 구현해야하는 이슈 체크리스트

- [x] 점주 새 주문 확인 api(polling)
- [x] 점주 accepted/rejected/completed 주문 목록 조회 api
- [x] 고객 주문 상태 확인 api(polling)
- [x] 점주 주문 상태 변경(requested -> accpeted) api
- [x] redis connection시 db 캐싱하는 로직

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

- OrderController v3로 분리한다.

**Comment by Gonnnnn** [comment]
아래 내용 추가
### redis 자료 구조
고객이 상태를 확인하기 위한 데이터와, 점주가 업데이트하는 데이터를 분리한다.
점주측은 cafe1Manager, 고객은 cafe1Client라는 key로 필드에 접근한다.
점주측 필드는 sortedset을 활용한다. sortedSet 내의 value 구조는 미정
고객은 set을 활용한다.
### 점주측 새 주문 확인 api
cursor 기반으로 동작한다.
새로고침, 로그인, 혹은 현재 아무 주문이 없다면 ''을, 그게 아니라면 현재 가지고 있는 주문 중 가장 높은 pk를 보낸다.
서버는 이를 확인하고, 해당 pk 이후의 주문 데이터를 '모두' 내려준다. (pagination x)
점주는 새로 내려진 데이터를 requested 목록에서 추가로 확인할 수 있다.
### 고객측 주문 상태 api
고객은 상태를 조회하고자 하는 주문의 id와 카페 id를 함께 보낸다.
redis에서 이를 조회한다. 없다면 캐싱
