### ISSUE TITLE
[BUG] : 리모트 서버 cors 이슈

### ISSUE THREAD

**Issue by Gonnnnn** [boostcampwm-2022/web29-Buddha#52]
## 💁 설명
- 리모트 서버에 배포하고, 로컬에서 해당 포트에 접속해 테스트하던 중 cors에러에 마주했다.

## 🎬 시나리오
1. 로그인 버튼 클릭
2. 네이버 로그인 진행 후, 회원가입 화면 혹은 상세 페이지 화면으로 전환

## 📢 예상 결과
- 네이버 로그인 진행 후, 회원가입 화면 혹은 상세 페이지 화면으로 전환

## 🃏 실제 결과
- cors에러 발생, 첫 페이지에서 페이지 전환이 되지 않는다. 상단에는 redirect uri만 떠있는 상태. 서버로부터 제대로된 응답이 오지 않아서이다.

**Comment by Gonnnnn** [comment]
서버측에서 cors origin을 지정하며 쉽게 해결할 수 있는 문제였다.

**Comment by qmdl980** [comment]
docker 내부 이미지가 업데이트 되지 않았던 것이 파악하기 쉽지 않아서 오래 걸렸음..!
- #53
