### ISSUE TITLE
[Feature] : DNS 도메인 적용

### ISSUE THREAD

**Issue by jinoo7099** [boostcampwm-2022/web29-Buddha#73]
## 💁 설명
- DNS 도메인 적용

## 📑 체크리스트
> 구현해야하는 이슈 체크리스트

- [x] 배포서버 IP 도메인 구하기
- [x] 배포서버에 도메인 적용하기

## 🚧 주의 사항
> 이슈를 구현할 때 유의깊게 살펴볼 사항

**Comment by qmdl980** [comment]
80번 포트로 바꾸기 잊지맙시다~~!

아키텍처도 아래와 같이 수정되어야 합니다
- NginX config에서 /api/* 로 오는 요청은 8080 포트에 바인드
- 이 외의 요청은 FE 번들링 파일 보내줄 수 있도록 설정 !
